### ISSUE TITLE
SyntaxError: Unexpected token function, when adding config.assets.js_compressor = :terser

### ISSUE THREAD

**Issue by ndvbd** [ahorek/terser-ruby#13]
When doing:
Rails.application.configure do
  config.assets.js_compressor = :terser
end

I get:

SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
(execjs):443

**Comment by ahorek** [comment]
do you have a recent [NodeJS](https://nodejs.org/en/download/) version? or mini_racer?

it looks like your runtime doesn't support ecma6 features...
